name: Test localTest.py execution

on:
  push:
    branches:
      - dev

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
      
    - name: setting envs in vm
      run: echo "${{secrets.ENVS_FILE }}" > .env
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Test the code
      run: |
        pip install python-dotenv
        python localTest.py
